apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kestra
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/kestra-gitops
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values-openshift.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: your-ocp-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
