securityContext:
  runAsNonRoot: true
  runAsUser: 1008630000
  fsGroup: 1008630000
  allowPrivilegeEscalation: false

postgresql:
  enabled: true
  auth:
    username: kestra
    password: k3str4
    database: kestra
  primary:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1008630000
      fsGroup: 1008630000
      allowPrivilegeEscalation: false

dind:
  enabled: false
