apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kestra
  namespace: ryan-nix-dev
spec:
  to:
    kind: Service
    name: kestra-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
