persistence:
  enabled: true
  existingClaim: kestra-storage

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      existingClaim: kestra-postgres
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false

elasticsearch:
  enabled: true
  volumeClaimTemplate:
    storageClassName: gp2
    resources:
      requests:
        storage: 10Gi

service:
  type: ClusterIP

route:
  enabled: false
