securityContext:
  runAsNonRoot: true
  runAsUser: 1008630000
  fsGroup: 1008630000
  allowPrivilegeEscalation: false

postgresql:
  auth:
    username: kestra
    password: k3str4
    database: kestra
  primary:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1008630000
      fsGroup: 1008630000
      allowPrivilegeEscalation: false
dind:
  enabled: false  # Disable Docker-in-Docker if not required
